### ISSUE TITLE
Can we create a gateway-addon-rust by extracting gateway.rs to a crate?

### ISSUE THREAD

**Issue by tsathishkumar** [hobinjk/mqtt-adapter#1]
I'm planning to write an adapter for MySensors, I see that I need to duplicate the gateway.rs code in this library. It would be great if we can extract it into a addon crate and then I can reuse it in my adapter.

**Comment by hobinjk** [comment]
I agree that extracting it would be good. I'm not sure what the state of this code is since I've been working on other parts of the Gateway. Unfortunately I don't have the time right now to spearhead the creation of gateway-addon-rust.

I also think that the [webthing-rust](https://github.com/mozilla-iot/webthing-rust/) model is a better approach in the long term as it uses the WoT API standard instead of the Gateway's unstable IPC format.

**Comment by tsathishkumar** [comment]
Ok, then I'll stick with webthing-rust for now.
